# Generated by Django 2.0.5 on 2019-01-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_log_corrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('PROGRESS', 'In Progress'), ('NOTSTARTED', 'Not Started')], max_length=25, null=True)),
                ('notes', models.TextField(null=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Log')),
            ],
        ),
    ]
