# Generated by Django 2.0.5 on 2018-07-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0010_tranline_closing_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranline',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
