# Generated by Django 2.0.5 on 2018-07-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0011_tranline_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranline',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tranline',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='tranline',
            name='tags',
        ),
    ]
